[windows]
3.89.229.87


[windows:vars]
ansible_user=Administrator
ansible_password=q=jN$FLMmBXhmknDn3mB;J(N.!*TZ!k.
ansible_port=5986
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
